
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ylhaart
 */
public class EditPersonGUI extends javax.swing.JFrame {

    /**
     * Creates new form EditPersonGUI
     */
    public EditPersonGUI() {
        initComponents();

        editDialog.pack();

        ClassLoader cl = getClass().getClassLoader();
        try {
            people = Person.loadPersons(cl.getResource("res/people.txt").openStream());
        } catch (IOException ex) {
            Logger.getLogger(EditPersonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        previousButton.setEnabled(false);
        updateUI();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editDialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        firstNameDialogField = new javax.swing.JTextField();
        lastNameDialogField = new javax.swing.JTextField();
        birthPlaceDialogField = new javax.swing.JTextField();
        birthCountryDialogField = new javax.swing.JTextField();
        birthYearDialogSpinner = new javax.swing.JSpinner();
        okDialogButton = new javax.swing.JButton();
        cancelDialogButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();

        editDialog.setModal(true);
        editDialog.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        jLabel2.setText(bundle.getString("EditPersonGUI.jLabel2.text")); // NOI18N

        jLabel3.setText(bundle.getString("EditPersonGUI.jLabel3.text")); // NOI18N

        jLabel4.setText(bundle.getString("EditPersonGUI.jLabel4.text")); // NOI18N

        jLabel5.setText(bundle.getString("EditPersonGUI.jLabel5.text")); // NOI18N

        jLabel6.setText(bundle.getString("EditPersonGUI.jLabel6.text")); // NOI18N

        firstNameDialogField.setText(bundle.getString("EditPersonGUI.firstNameDialogField.text")); // NOI18N

        lastNameDialogField.setText(bundle.getString("EditPersonGUI.lastNameDialogField.text")); // NOI18N

        birthPlaceDialogField.setText(bundle.getString("EditPersonGUI.birthPlaceDialogField.text")); // NOI18N

        birthCountryDialogField.setText(bundle.getString("EditPersonGUI.birthCountryDialogField.text")); // NOI18N

        birthYearDialogSpinner.setModel(new javax.swing.SpinnerNumberModel(1900, 1900, 2016, 1));

        okDialogButton.setText(bundle.getString("EditPersonGUI.okDialogButton.text")); // NOI18N
        okDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okDialogButtonActionPerformed(evt);
            }
        });

        cancelDialogButton.setText(bundle.getString("EditPersonGUI.cancelDialogButton.text")); // NOI18N
        cancelDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelDialogButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editDialogLayout = new javax.swing.GroupLayout(editDialog.getContentPane());
        editDialog.getContentPane().setLayout(editDialogLayout);
        editDialogLayout.setHorizontalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addComponent(cancelDialogButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okDialogButton))
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(birthPlaceDialogField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(birthCountryDialogField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(birthYearDialogSpinner, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastNameDialogField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(firstNameDialogField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49))
        );
        editDialogLayout.setVerticalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstNameDialogField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastNameDialogField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(birthPlaceDialogField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(birthCountryDialogField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(birthYearDialogSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okDialogButton)
                    .addComponent(cancelDialogButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(bundle.getString("EditPersonGUI.title")); // NOI18N

        jLabel1.setText(bundle.getString("EditPersonGUI.jLabel1.text")); // NOI18N

        firstNameLabel.setText(bundle.getString("EditPersonGUI.firstNameLabel.text")); // NOI18N

        lastNameLabel.setText(bundle.getString("EditPersonGUI.lastNameLabel.text")); // NOI18N

        editButton.setText(bundle.getString("EditPersonGUI.editButton.text")); // NOI18N
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        nextButton.setText(bundle.getString("EditPersonGUI.nextButton.text")); // NOI18N
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        previousButton.setText(bundle.getString("EditPersonGUI.previousButton.text")); // NOI18N
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(firstNameLabel))
                    .addComponent(previousButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lastNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(editButton))
                    .addComponent(nextButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(firstNameLabel)
                    .addComponent(lastNameLabel)
                    .addComponent(editButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton)
                    .addComponent(previousButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        editDialog.setVisible(true);
    }//GEN-LAST:event_editButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        current--;

        if (current < people.size()) {
            nextButton.setEnabled(true);
        }

        if (current == 0) {
            previousButton.setEnabled(false);
        }

        updateUI();
    }//GEN-LAST:event_previousButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        current++;

        if (current > 0) {
            previousButton.setEnabled(true);
        }

        if (current == people.size() - 1) {
            nextButton.setEnabled(false);
        }
        updateUI();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void cancelDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelDialogButtonActionPerformed
        editDialog.setVisible(false);
    }//GEN-LAST:event_cancelDialogButtonActionPerformed

    private void okDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okDialogButtonActionPerformed
        storeChanges();
        updateUI();
        editDialog.setVisible(false);
    }//GEN-LAST:event_okDialogButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPersonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPersonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPersonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPersonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPersonGUI().setVisible(true);
            }
        });
    }

    private void updateUI() {
        Person p = people.get(current);

        firstNameLabel.setText(p.getFirstName());
        lastNameLabel.setText(p.getLastName());

        firstNameDialogField.setText(p.getFirstName());
        lastNameDialogField.setText(p.getLastName());
        birthPlaceDialogField.setText(p.getBirthTown());
        birthCountryDialogField.setText(p.getBirthCountry());
        birthYearDialogSpinner.setValue(p.getBirthYear());
    }

    private void storeChanges() {
        Person person = people.get(current);
        person.setFirstName(firstNameDialogField.getText());
        person.setLastName(lastNameDialogField.getText());
        person.setBirthTown(birthPlaceDialogField.getText());
        person.setBirthCountry(birthCountryDialogField.getText());
        person.setBirthYear((int) birthYearDialogSpinner.getValue());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField birthCountryDialogField;
    private javax.swing.JTextField birthPlaceDialogField;
    private javax.swing.JSpinner birthYearDialogSpinner;
    private javax.swing.JButton cancelDialogButton;
    private javax.swing.JButton editButton;
    private javax.swing.JDialog editDialog;
    private javax.swing.JTextField firstNameDialogField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField lastNameDialogField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton okDialogButton;
    private javax.swing.JButton previousButton;
    // End of variables declaration//GEN-END:variables

    List<Person> people;
    int current;
}
